# System Configuration
driver:
  host: "localhost"
  port: 5001

# MapReduce Configuration
mapreduce:
  num_map_tasks: 6    # N
  num_reduce_tasks: 4  # M

# File System Configuration
directories:
  input: "../files/inputs"
  intermediate: "../files/intermediate"
  output: "../files/out"

# Task Configuration
task_settings:
  retry_attempts: 3
  retry_delay: 5  # seconds
